import ollama
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from dataset.build_vectordb import AviationTextNormalizer

class LocalAviationRAG:
    def __init__(self, db_path="./qdrant_aviation_db", collection_name="asrs_incidents", model_name="llama3"):
        print("Initializing Local RAG Engine...")
        self.model = SentenceTransformer("BAAI/bge-small-en-v1.5")
        self.qdrant = QdrantClient(path=db_path)
        self.collection_name = collection_name
        self.normalizer = AviationTextNormalizer()
        self.llm_model = model_name

    def retrieve_context(self, user_query: str, top_k: int = 3):
        # Normalize and vectorize incoming user query
        cleaned_query = self.normalizer.process_narrative(user_query)
        query_vector = self.model.encode(cleaned_query).tolist()
        
        # Fixed: Using the unified query_points method instead of the removed search method
        search_results = self.qdrant.query_points(
            collection_name=self.collection_name,
            query=query_vector,
            limit=top_k,
            with_payload=True
        ).points
        
        # Build context blocks from payload text fields
        retrieved_contexts = []
        for index, point in enumerate(search_results):
            payload = point.payload
            context_block = (
                f"--- Reference Document {index + 1} (ID: {payload['record_id']}) ---\n"
                f"Aircraft: {payload['aircraft_make']}\n"
                f"Narratives: {payload['text']}\n"
            )
            retrieved_contexts.append(context_block)
            
        return "\n".join(retrieved_contexts)

    def generate_answer(self, user_query: str):
        # 1. Fetch relevant background documentation
        context = self.retrieve_context(user_query, top_k=2)
        
        # 2. Frame the query using defensive system instructions
        system_instruction = (
            "You are an expert aviation safety investigator and maintenance AI assistant. "
            "Your task is to answer the user's technical query using ONLY the provided incident reference documents. "
            "If the documents do not contain enough specific operational facts to answer the question, "
            "state clearly that you lack sufficient data. Do not make up facts or extrapolate beyond the text.\n\n"
            f"=== CONTEXT DOCUMENTS ===\n{context}\n"
        )
        
        print(f"\n[Query]: {user_query}")
        print("[System]: Querying local LLM via Ollama (Streaming Response)...\n")
        
        # 3. Stream the output from the local model container
        response_stream = ollama.chat(
            model=self.llm_model,
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": user_query}
            ],
            stream=True
        )
        
        # Print tokens as they are generated by your hardware
        for chunk in response_stream:
            print(chunk['message']['content'], end='', flush=True)
        print("\n")

# if __name__ == "__main__":
#     rag_system = LocalAviationRAG(model_name="llama3")
#     try:
#         rag_system.generate_answer("What is the recommended financial compensation protocol for passengers who miss their connecting flights due to an emergency diversion caused by an engine failure?")
#     finally:
#         # Explicitly close the internal Qdrant storage engine before the script terminates
#         if hasattr(rag_system.qdrant, 'close'):
#             rag_system.qdrant.close()
#             print("[System]: Qdrant storage connection closed cleanly.")